# 
# Vagrantfile per un doppio nodo (docker):
# sul primo è installato Docker e Docker Compose.   
# Sul secondo c'è esclusivamente Java, fungerà da client. 
# Basata su Ubunty 16.04 LTS. 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-16.04"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"

    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/_shared/resources e /home/asw/_shared/scripts) 
    config.vm.synced_folder "../_shared/", "/home/asw/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "docker", che prevede: 
    # - Docker 
	# - Docker Compose 
    #

    config.vm.define "docker" do |node|
        node.vm.hostname = "docker"    
        node.vm.network "private_network", ip: "10.11.1.121", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
			v.cpus = 2
            v.memory = 2048  
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
		# 8080 -> 8081 per evitare conflitti sulla porta 8080 con altre vm  
        node.vm.network "forwarded_port", guest: 8080, host: 8081, id: 'http', auto_correct: true

		# installa docker e docker compose 
        node.vm.provision :shell, path: "../_shared/scripts/setup-docker.sh"

		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo docker del progetto asw Wildfly completata'"

    end

    #
    # Configurazione del nodo "client", che prevede:  
    # - Java
    #

    config.vm.define "client" do |node|
        node.vm.hostname = "client"    
        node.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        node.vm.provision :shell, :inline => "echo '10.11.1.101 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.201 client' >> /etc/hosts"

		# installa docker e docker compose 
        node.vm.provision :shell, path: "../_shared/scripts/setup-docker.sh"

		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo client del progetto asw Wildfly completata'"

    end

end
