# 
# Vagrantfile per un singolo nodo
# per il deploy di un war 
# in un application server Wildfly 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-16.04"

    
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"
    config.vm.synced_folder "../_shared/", "/home/asw-project-wildfly/_shared", :mount_options => ["dmode=777", "fmode=777"]

  
    config.vm.synced_folder "../../projects/", "/home/asw-project-wildfly/projects", :mount_options => ["dmode=777", "fmode=777"]

    config.vm.synced_folder "../_shared/scripts/", "/home/asw-project-wildfly/script", :mount_options => ["dmode=777", "fmode=777"]


    #
    # Configurazione del nodo "virtualmachine", che prevede: 
    # - Oracle Java SDK 8 
    # - Wildfly
	#

    config.vm.define "virtualmachine" do |node|
        node.vm.hostname = "virtualmachine"    
        node.vm.network "private_network", ip: "10.11.1.51", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            # queste risorse bastano nella maggior parte dei casi
			v.memory = 1536 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true

        #wildfly
        node.vm.network :forwarded_port, host: 9994, guest: 9994
        node.vm.network :forwarded_port, guest: 8080, host: 8088, id: 'http', auto_correct: true
        node.vm.network :forwarded_port, guest: 28080, host: 8081, id: 'http', auto_correct: true

        # provisioning con bash 
        
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java-vm.sh"      
        node.vm.provision :shell, path: "../_shared/scripts/setup-wildfly.sh"



		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw-project-wildfly/projects projects'

		
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo virtualmachine del progetto asw Wildfly completata'"

    end
end

